UW-Madison-DoIT/my-profile

my-profile-webapp/src/main/webapp/my-app.js
Turns on portal search for demo
=> Search by last name

my-profile-api/src/main/java/edu/wisc/my/profile/model/ContactInformation.java, my-profile-api/src/main/java/edu/wisc/my/profile/service/EmergencyContactInformationService.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/KeyValueDataStoreDao.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/emergency/dao/ContactInformationArrayExtractor.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/emergency/dao/EmergencyContactInformationDao.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/emergency/dao/EmergencyContactInformationDaoImpl.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/emergency/service/EmergencyContactInformationServiceImpl.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/local/dao/LocalContactInformationDaoImpl.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/EmergencyContactInformationController.java, my-profile-webapp/src/main/resources/README.md, my-profile-webapp/src/main/webapp/WEB-INF/context/applicationContext.xml
+ Adds relationship (String) and languages (`TypeValue` array) following elements to the `ContactInformation` object.
+ Creates service and dao for Emergency Contact
+ Creates key/val dao impl for emergency contact
+ Creates controller for Emergency Contact save/get
GET: `/profile/api/emergencyContactInfo/get.json`
POST: `/profile/api/emergencyContactInfo/set`
Data should be a `ContactInformation[]`
=> MUMPFL-42 : Add in emergency contact lookup/save for key/val

my-profile-webapp/src/main/webapp/my-app.js, my-profile-webapp/src/main/webapp/partials/emergency.html
Also limits the number of phone numbers to 3. This is part of the polish for emergency contact, more polish will be coming soon in a pull request near you.
=> MUMPFL-65: Add email and remove address from emergency contact

my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency.html, my-profile-webapp/src/main/webapp/my-app/profile/partials/address.html, my-profile-webapp/src/main/webapp/partials/address.html
Sorry @jhanstra, couldn't get https://github.com/UW-Madison-DoIT/my-profile/pull/11 working, so just cherrypicked your commits to a new branch.
Will close https://github.com/UW-Madison-DoIT/my-profile/pull/11 when a couple of other eyes are on this to make sure that this is indeed a replacement for https://github.com/UW-Madison-DoIT/my-profile/pull/11
Now, it's time for some loading interactions.
=> Polish sausage

my-profile-webapp/src/main/webapp/css/my-app.less, my-profile-webapp/src/main/webapp/my-app/lec/partials/admin-lookup.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html, my-profile-webapp/src/main/webapp/my-app/profile/partials/main.html
- Margin around the alert
- Bold search and better wording to be more action-oriented
- Placeholder text in search box
- Clean up in the code to not use inline styles
=> Tweaks to Admin Lookup based on Phyllis' suggestions

my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html
This makes the loading icon functional in each column. It's hard to demonstrate because it loads so fast, but I've seen it work. :)
=> MUMPFL-70: Loading icon fix

my-profile-api/src/main/java/edu/wisc/my/profile/model/User.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/local/dao/LocalUserDaoImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/SearchUsersProcedure.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/service/LocalContactInformationServiceImpl.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/LocalContactAdminController.java, my-profile-webapp/src/main/resources/users.json
Updates the user object. Made sure it works with both middleware and local impl.  Took out developer names in the users.json file.
=> Changes the User object to reflect actual user

my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/local/dao/LocalUserDaoImpl.java, my-profile-webapp/src/main/webapp/my-app/lec/controllers.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/admin-lookup.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/user.html, my-profile-webapp/src/main/webapp/my-app/lec/services.js
Search doesn't use portal anymore, only uses the controller search.
=> Swtiches search to controller search

my-profile-webapp/src/main/webapp/js/app-config.js, pom.xml
=> MUMMNG-1707 : Upgrade to 4.1.1.24

my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html
=> Update wording in description

my-profile-webapp/src/main/webapp/js/app-config.js
=> MUMPFL-108 Removes Beta Header

my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/SearchUsersProcedure.java
Hey, let's use a newer version of this function!
=> Updates search function to latest version

my-profile-webapp/src/main/webapp/my-app/lec/partials/address.html
=> MUMPFL-101 Adds descriptive text

my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html
=> MUMPFL-124 Adds more text to information area

my-profile-webapp/src/main/java/edu/wisc/my/profile/web/EmergencyPhoneNumberController.java, my-profile-webapp/src/main/webapp/my-app/lec/controllers.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-phone.html
+ Created centralized error message container on LEC
+ If error comes back from service, notify user of error and keep them in edit mode of whatever they were doing at that time.
Example error message when couldn't save the local address
=> MUMPFL-127 : Inform students about errors persisting their data

my-profile-webapp/src/main/webapp/my-app/lec/partials/address.html, my-profile-webapp/src/main/webapp/my-app/profile/partials/address.html
Before you could enter zip codes that were very long.  Based on feedback, MUMPFL-134 was created to limit the input to 10 characters
=> MUMPFL-134 Set max length of zip input to 10

my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html
Switches order of elements for the ease of customers entering information.
Before:
After:
=> MUMPFL-133 Switch order of emergency elements

my-profile-webapp/src/main/webapp/js/app-config.js, pom.xml
+ Upgrade frame from `1.0.0` to `1.1.0`
=> MUMUP-2129 : upgrade to 1.1.0 frame

my-profile-api/src/main/java/edu/wisc/my/profile/model/SearchTerm.java
Adds a routine `toString()` implementation to `SearchTerm`, which should make log messages like this (generated today in production):
```
2015-10-15 09:24:17,406 [ajp-nio-127.0.0.1-8009-exec-92] INFO  e.w.m.p.s.SearchUsersServiceImpl - User apetro looked up users using this search term: edu.wisc.my.profile.model.SearchTerm@3145b23d.
```
more useful.
=> Implement toString() in SearchTerm.

my-profile-webapp/src/main/webapp/my-app/lec/controllers.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html
Before each module had its own loading gif and it looked... funky.
Now I created a singular loading gif, if any of them are initing.
=> MUMPFL-96 : Clean up loading state

my-profile-api/src/main/java/edu/wisc/my/profile/model/ContactAddress.java, my-profile-api/src/main/java/edu/wisc/my/profile/model/ContactInformation.java, my-profile-api/src/main/java/edu/wisc/my/profile/model/TypeValue.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/EmergencyContactInformationController.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/EmergencyPhoneNumberController.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/LocalContactInformationController.java
Creates a string suitable for logging.  Masks sensitive information per the request of UW Security.
Also logs less on info, and logs the data on error.
Before on emergency contact:
`
[{"edit":true,"preferredName":"Timothy A Vertein","relationship":"Spouse","comments":"","phoneNumbers":[{"type":"mobile","value":"6081234567"}],"emails":[{"type":"primary","value":"jim@googlen.com"}],"addresses":[]}, {"edit":false,"preferredName":"Timothy A Vertein","relationship":"Parent","comments":"","phoneNumbers":[{"type":"mobile","value":"6081234567"},{"type":"mobile","value":"6081234567"},{"type":"mobile","value":"asdfasdf"}],"emails":[{"type":"primary","value":"jim@googlen.com"}],"addresses":[]}, {"edit":false,"preferredName":"Timothy A Vertein","relationship":"Parent","comments":"","phoneNumbers":[{"t …
=> MUMPFL-137 Masks Sensitive Data for Logging

my-profile-webapp/src/main/webapp/js/app-config.js, pom.xml
=> Upgrade to frame 1.3.3

my-profile-api/src/main/java/edu/wisc/my/profile/model/User.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/SearchUsersProcedure.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/LocalContactAdminController.java, my-profile-webapp/src/main/resources/users.json, my-profile-webapp/src/main/webapp/my-app/lec/partials/user.html
Before:
large screen:
small screen:
After:
large screen:
small screen:
=> Campus id here we come

my-profile-api/pom.xml, my-profile-api/src/main/java/edu/wisc/my/profile/model/ContactAddress.java, my-profile-api/src/main/java/edu/wisc/my/profile/model/ContactInformation.java, my-profile-api/src/main/java/edu/wisc/my/profile/model/TypeValue.java, my-profile-api/src/test/java/edu/wisc/my/profile/model/ContactAddressTest.java, my-profile-api/src/test/java/edu/wisc/my/profile/model/ContactInformationTest.java, my-profile-api/src/test/java/edu/wisc/my/profile/model/TypeValueTest.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/EmergencyContactMiddlewareDaoImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/EmergencyPhoneNumberDaoImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/LocalContactMiddlewareDaoImpl.java, pom.xml
Middleware's saving information endpoint always returns success, regardless of whether or not it was actually successful.  This saves, then calls the MW layer to see what was saved and validates against it.
=> MUMPFL-139 Validates MW Saving Function

my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html
Changes it from a variable called `contact-info` to a string of the same name.
=> Fixing fname variable

my-profile-webapp/src/main/webapp/my-app/lec/partials/address.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/admin-lookup.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-phone.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/user.html
Before:
After:
Feels like edit and delete should be raised.  Also phone numbers should work
=> MUMPFL-144 Raises buttons and fixes ng-switch bug

my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-phone.html
RegEx allows alphanumerics, and some special characters, but no slashes, and no emoji.
=> added RegEx

my-profile-webapp/src/main/webapp/css/my-app.less, my-profile-webapp/src/main/webapp/js/override.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/address.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency.html, pom.xml
**In this PR**:
- Update to [uw-frame version 5.0.0](https://github.com/UW-Madison-DoIT/uw-frame/releases)
- Adjust `override.js` to cope with version change
- Cosmetic adjustments to make lists of addresses/contacts more readable and responsive
*Note: Notifications bell won't work until `staticFeeds/messages.json` is added to angularjs-portal overlay in prod ([see #288](https://git.doit.wisc.edu/myuw-overlay/angularjs-portal/merge_requests/288)).*
=> Update to latest version of uw-frame

my-profile-webapp/src/main/webapp/my-app/lec/controllers.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html, my-profile-webapp/src/main/webapp/my-app/lec/services.js
Building all the error messages in a service.
=> standardizing the error calls in LEC

my-profile-webapp/src/main/webapp/my-app/lec/partials/admin-lookup.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html, my-profile-webapp/src/main/webapp/my-app/profile/partials/main.html, my-profile-webapp/src/main/webapp/my-app/profile/partials/settings.html, pom.xml
Updating up to 7.0.0 before running a release
=> chore: update to frame 7.0.0

my-profile-webapp/src/main/webapp/js/override.js
Trivial. Fixes agreement in number in description of a beta setting.
=> docs: parts that *are* hidden, not parts that *is* hidden

README.md, my-profile-webapp/pom.xml, my-profile-webapp/src/main/webapp/css/my-app.less, my-profile-webapp/src/main/webapp/js/override.js, my-profile-webapp/src/main/webapp/my-app/dialog/controllers.js, my-profile-webapp/src/main/webapp/my-app/dialog/partials/help-dialog-template.html, my-profile-webapp/src/main/webapp/my-app/lec/controllers.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-phone.html, my-profile-webapp/src/main/webapp/my-app/main.js, my-profile-webapp/src/main/webapp/my-app/menu/controllers.js, my-profile-webapp/src/main/webapp/my-app/menu/side-navigation.html, pom.xml
[MUMMNG-4158](https://jira.doit.wisc.edu/jira/browse/MUMMNG-4158): "As a student registering emergency contact info I'd like /profile to use latest uPortal-app-framework so that I can enjoy the best available emergency contact registration experience."
**In this PR:**
- Update to uportal-app-framework v9.0.1
- Add side navigation menu
- Add help dialog
- Switch from cards presentation to simpler column layout 
- Other visual updates to be more in sync with MyUW
**See also:** [Companion PR for predev tier](https://git.doit.wisc.edu/myuw-overlay/my-profile/merge_requests/21)
=> Update to latest app framework version

.editorconfig, my-profile-webapp/src/main/webapp/my-app/lec/controllers.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-phone.html
**In this PR**:
- Phone number panel shows up on data/error/empty
- Reverted change that broke error communication
=> Fix phone number not showing on error

my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-phone.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency.html
**In this PR:**
- Spacing between lines in emergency contact
- Disable add button if phone number already exists
=> Fix appearance of emergency contact

my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-phone.html
**In this PR:**
- Show empty state when user hasn't entered a phone number
=> fix: show empty state when no phone number

my-profile-webapp/src/main/webapp/my-app/app-config.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/address.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-phone.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency.html, my-profile-webapp/src/main/webapp/my-app/main.js
**In this PR:**
- Add `ngMessages` dependency for finding and displaying form errors
- "Save" button is disabled if any fields don't meet validation requirements
- Perform the following validation checks:
- All required fields
- Address, city, zip, and comments max length
- Phone numbers contain only numbers
- Email address must be valid (per W3C standard)
Validating required and length:
Validating format:
Form submission disabled if any fields don't meet requirements:
=> Add live form validation

my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html
corrects the URL for the new SIS link
=> MUMMNG-4670 correct url

CHANGELOG.md, my-profile-middleware-impl/pom.xml
[MYUWADMIN-1007](https://jira.doit.wisc.edu/jira/browse/MYUWADMIN-1007)
=> upgrade to ojdbc8 19.6.0.0 provided
