UW-Madison-DoIT/my-profile

my-profile-api/src/main/java/edu/wisc/my/profile/model/ContactInformation.java, my-profile-webapp/src/main/webapp/css/app.less, my-profile-webapp/src/main/webapp/my-app.js, my-profile-webapp/src/main/webapp/partials/emergency.html
In this pull request:
- Dropped languages array in favor of a free-form response for comments and considerations for communication. Given label "Communication considerations / other comments". @keirserrie let me know if there's a better or shorter label that makes sense for this, same with the placeholder text.
- Added line by line validation and form feedback for the user. If a user skips through a required field it will yell at you (gently :smile:)
- Input field widths vary according to the length of the content that will be in it
- Asterisks on required fields. Right now we are requiring Name, Primary Phone Number & Type, Email, and Relationship
- Dropped placeholder text for phone number until we have validation for it, as it confuses the user
- Distinct wording on 'Primary Phone' vs. …
=> More polish

Dockerfile, tomcat-users.xml
Adds in a simple Dockerfile for future deployment options.
=> MUMMNG-1681 : Dockerfile

my-profile-api/src/main/java/edu/wisc/my/profile/model/User.java, my-profile-api/src/main/java/edu/wisc/my/profile/service/LocalContactInformationService.java, my-profile-api/src/main/java/edu/wisc/my/profile/service/SearchUsersService.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/local/service/LocalContactInformationServiceImpl.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/service/SearchUsersServiceImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/SearchUsersMiddlewareDao.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/SearchUsersMiddlewareDaoImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/SearchUsersProcedure.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/service/LocalContactInformationServiceImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/service/SearchUsersServiceImpl.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/LocalContactAdminController.java, my-profile-webapp/src/main/resources/placeholder.properties, my-profile-webapp/src/main/webapp/WEB-INF/context/applicationContext.xml
Adds a dao to do middleware integration for search.
=> Mw integration

my-profile-webapp/src/main/webapp/css/my-app.less, my-profile-webapp/src/main/webapp/my-app/lec/controllers.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/user.html
Adds emergency contact cards under the local address cards in the admin interface. 
Adds descriptive text to the cards for emergency contact and local address to inform the user what they are, per @keirserrie's mockups.
Thanks to @vertein for creating the back end!
=> MUMPFL-24, 74, 75: Admin Emergency Contact UI and Descriptive Text for LEC

my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/mapper/ContactInformationMapper.java, pom.xml
=> Comment escape char

my-profile-api/pom.xml, my-profile-api/src/main/java/edu/wisc/my/profile/model/TypeValue.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/mapper/ContactInformationMapper.java, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency.html
+ Changes all non-zero phone numbers to optional
+ Adds trash button to non-zero phone numbers
+ Removes "add another" after 3 are on the screen
+ Allows you to submit an empty phone number, as long as zero is filled out
+ Doesn't save said zero phone number
+ Doesn't show an empty phone number in the view mode
=> MUMPFL-81 Cleanup phone number fields

my-profile-api/src/main/java/edu/wisc/my/profile/model/SearchTerm.java, my-profile-api/src/main/java/edu/wisc/my/profile/service/SearchUsersService.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/local/dao/LocalUserDao.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/local/dao/LocalUserDaoImpl.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/service/SearchUsersServiceImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/SearchUsersMiddlewareDao.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/SearchUsersMiddlewareDaoImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/service/SearchUsersServiceImpl.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/LocalContactAdminController.java, my-profile-webapp/src/main/webapp/css/my-app.less, my-profile-webapp/src/main/webapp/my-app/lec/controllers.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/admin-lookup.html, my-profile-webapp/src/main/webapp/my-app/lec/services.js
Adds in the ability to optionally search by first name.
Before UI:
After UI:
@jhanstra has graciously volunteered to work on MUMPFL-105 to update the UI when he is available.
=> MUMPFL-83 Search optionally by first name

my-profile-webapp/src/main/webapp/my-app/lec/constants.js, my-profile-webapp/src/main/webapp/my-app/lec/controllers.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/address.html
+ Country is now preselected as USA for new form
+ State is now preselected as WI for new form
+ Fix country order (now A-Z)
+ Fix State Order (now A-Z)
+ Clean up empty state ... of state when a country doesn't have state/province/regions... in our database
=> MUMPFL-110 : Fix state country drop downs

my-profile-webapp/src/main/webapp/css/my-app.less, my-profile-webapp/src/main/webapp/my-app/lec/controllers.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/address.html
+ Sets `readOnly` on `type=HOUSING`
+ Creates flag of `housing` that is set to true if `type=HOUSING` for message and add buttons
=> MUMPFL-86 : Add in housing RO addresses

my-profile-webapp/pom.xml, my-profile-webapp/src/main/webapp/my-app/lec/partials/user.html
Added div for Local Phone Numbers that is between local addresses and emergency info people
=> MUMPFL-125 : Admin wants phone numbers

my-profile-api/src/main/java/edu/wisc/my/profile/model/TypeValue.java, my-profile-api/src/main/java/edu/wisc/my/profile/service/EmergencyPhoneNumberService.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/emergency/service/EmergencyContactInformationServiceImpl.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/emergencyPhone/dao/EmergencyPhoneNumberDao.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/emergencyPhone/dao/EmergencyPhoneNumberDaoImpl.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/emergencyPhone/dao/EmergencyPhoneNumberExtractor.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/emergencyPhone/service/EmergencyPhoneNumberServiceImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/EmergencyContactMiddlewareDaoImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/EmergencyPhoneNumberDao.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/EmergencyPhoneNumberDaoImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/EmergencyPhoneNumberResultSetExtractor.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/LocalContactMiddlewareDaoImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/mapper/ContactInformationMapper.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/service/EmergencyPhoneNumberServiceImpl.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/EmergencyPhoneNumberController.java, my-profile-webapp/src/main/webapp/WEB-INF/context/applicationContext.xml, my-profile-webapp/src/main/webapp/my-app/lec/controllers.js, my-profile-webapp/src/main/webapp/my-app/lec/directives.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-phone.html, my-profile-webapp/src/main/webapp/my-app/lec/services.js
Screenshots
New:
Clean State:
Stacks on screen size small now:
Looks like someone should add a phone number:
Looks like you need a type before clicking that save button:
State with information entered:
And you can always hit update and go back and update (but not delete):
Loading state:
=> Students have phones too

my-profile-api/src/main/java/edu/wisc/my/profile/service/EmergencyPhoneNumberService.java, my-profile-local-contact-impl/src/main/java/edu/wisc/my/profile/emergencyPhone/service/EmergencyPhoneNumberServiceImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/service/EmergencyPhoneNumberServiceImpl.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/LocalContactAdminController.java, my-profile-webapp/src/main/webapp/my-app/lec/partials/user.html
Now that https://github.com/UW-Madison-DoIT/my-profile/pull/40  is done, the backend for https://github.com/UW-Madison-DoIT/my-profile/pull/39 could be done and verified.
Sorry no screenshots.  Nothing changed in the UI.
=> Admin gets to see phone numbers

my-profile-api/pom.xml, my-profile-api/src/main/java/edu/wisc/my/profile/model/ContactInformation.java, my-profile-api/src/main/java/edu/wisc/my/profile/model/TypeValue.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/EmergencyContactInformationController.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/EmergencyPhoneNumberController.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/LocalContactInformationController.java, my-profile-webapp/src/main/webapp/my-app/lec/partials/address.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency.html, pom.xml
Bug - Saving a comment over a certain length resulted in an error. :(
Solution - Update front end to reflect the back end limits and improve logging to capture what users are typing for comments.
Before UI had no character limit for emergency contact and the char limit for local was 100.
Trying to save longer than that would get you a nice error message.
now!
=> MUMPFL-129 Save Bug with Comment Lengths

my-profile-webapp/src/main/java/edu/wisc/my/profile/web/LocalContactAdminController.java, my-profile-webapp/src/main/webapp/my-app/lec/controllers.js
Before if there was an error retrieving data from a database (such as a timeout error), we would tell the user it was a permission error.  No More.
Before:
After:
=> MUMPFL-126 Disambigute db error from permission

my-profile-api/src/main/java/edu/wisc/my/profile/model/User.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/SearchUsersProcedure.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/LocalContactAdminController.java, my-profile-webapp/src/main/resources/users.json, my-profile-webapp/src/main/webapp/my-app/lec/partials/user.html
=> MUMPFL-115 Show student birthdate

.travis.yml, README.md, pom.xml
Adds `.travis.yml` configuration so that `travis-ci.org` will build each branch and pull request.
Builds only modules that do not require the not-in-public-Maven-repos Oracle database driver .jar.
See also [Travis working on my fork of this repo](https://travis-ci.org/apetro/my-profile).
=> Add travis-ci continuous integration

my-profile-api/src/main/java/edu/wisc/my/profile/model/ContactInformation.java, my-profile-api/src/test/java/edu/wisc/my/profile/model/ContactInformationTest.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/EmergencyContactMiddlewareDaoImpl.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/dao/LocalContactMiddlewareDaoImpl.java
Before the MW Validation would always fail on initial save. The data would actually save, just when we verified it, it would tell the user that it didn't save.  You can tell that it saved, because when you refreshed the page, your save would appear, and the database confirmed.  This was caused because we pass in values to MW, and MW says, "ha, we will save things differently".
Oddly enough, this code catches a newly found Middleware bug
If you have something saved, and you try to delete just your comment, the save then fails.  I'll alert the right people, but I guess, good for us?
=> Mw saves funny

.travis.yml
`code.doit` stopped being publicly visible, but the build depends on it, so build now fails from travis's perspective.
(This also means the build is broken from the perspective of anyone outside of UW-Madison, which impairs thinking about `my-profile` as something that could grow to adoption beyond MyUW...)
=> Drop travis.yml to disable travis-ci since false-fails due to code.doit.

my-profile-webapp/src/main/webapp/css/my-app.less, my-profile-webapp/src/main/webapp/my-app/lec/controllers.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/address.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-phone.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency.html
[MUMPFL-153](https://jira.doit.wisc.edu/jira/browse/MUMPFL-153): "As a student accessing Local/Emergency Contact, I would like to be reminded of the opportunity to register my cell phone for WiscAlerts, so that I can understand the relationship between these registrations and successfully enable the university to contact me in an emergency."
**In this PR**:
- Add message directing people to the WiscAlert portlet to opt-in
- Cosmetic updates
- Normal spacing in material forms
- Repeat blocks of info instead of entire cards
- Icon buttons with tooltips for edit/delete
(*note: the WiscAlert message in the first screenshot is from a previous commit*)
=> Add wiscalert message and update design

my-profile-api/pom.xml, my-profile-api/src/main/java/edu/wisc/my/profile/log/MaskedLoggable.java, my-profile-api/src/main/java/edu/wisc/my/profile/log/MaskedLoggables.java, my-profile-api/src/main/java/edu/wisc/my/profile/model/ContactAddress.java, my-profile-api/src/main/java/edu/wisc/my/profile/model/ContactInformation.java, my-profile-api/src/main/java/edu/wisc/my/profile/model/TypeValue.java, my-profile-middleware-impl/src/main/java/edu/wisc/my/profile/mapper/ContactInformationMapper.java, my-profile-webapp/pom.xml, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/EmergencyContactInformationController.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/EmergencyPhoneNumberController.java, my-profile-webapp/src/main/java/edu/wisc/my/profile/web/LocalContactInformationController.java, my-profile-webapp/src/main/webapp/my-app/lec/controllers.js, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-info.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency-phone.html, my-profile-webapp/src/main/webapp/my-app/lec/partials/emergency.html, pom.xml
Error Messaging much more visible:
And UTF-8 Characters are retained through the process:
Included:
* Server-side controllers responding with last saved object on set
* String masking pulled out to an interface
* Fix for small front-end syntax error
* Client-side error notification is now a dialog box controlled by events
* Fix for just including _any_ UTF-8 characters that caused the service to break.
would be nice to have:
* Client-side to verify fields of last saved object against the fields it has
* Reduce down to one properly configured JSON serializer, rather than three
* Verify we're using Java 8 to build and run, then use streams rather than guava
=> MUMPFL-157 server-side controllers responding with the last saved object on set

my-profile-webapp/src/main/resources/logback.xml
I got annoyed that the `run_local.sh` was pumping logs into the sources directory, making the logs dir immune to `mvn clean`
This fixes that by using `${catalina.base}` to find the tomcat's log directory, placing the logs in `target/tomcat/logs`
This also includes some editor enforced whitespace changes.
=> using catalina.base to set log directory
